owner: that-dude-from-tes
repo: website-monitor

sites:
  - name: EventCrafter Weddings
    url: https://weddingsbyeventcrafter.com/
    # If the site gives 502/500, it sends an alert
    expectedStatusCodes:
      - 200
    # Increase timeout to 60s to prevent false alarms
    maxResponseTime: 60000

status-website:
  cname: ""
  baseUrl: /website-monitor
  theme: light
  name: Uptime Status

# This config cleans up the log text in your repo
commitMessages:
  readmeContent: ":pencil: Update Readme with current downtime stats"
  summaryJson: ":card_file_box: Update status summary data"
  statusChange: ":rotating_light: Status change detected"
  graphsUpdate: ":chart_with_upwards_trend: Update uptime graphs"
  commitAuthorName: "Uptime Bot"
  commitAuthorEmail: "uptime@b-cdn.net"
