
owner: that-dude-from-tes
repo: website-monitor
sites:
  - name: EventCrafter Weddings
    url: https://weddingsbyeventcrafter.com/
    expectedStatusCodes:
      - 200
    # timeout in case the site is slow (avoiding false alarms)
    maxResponseTime: 60000 
    icon: https://weddingsbyeventcrafter.com/favicon.ico

status-website:
  cname: ""
  baseUrl: /website-monitor 
  theme: light
  name: Uptime Status

# This cleans up the logs
commitMessages:
  readmeContent: ":pencil: Update Readme with current downtime stats"
  summaryJson: ":card_file_box: Update status summary data"
  statusChange: ":rotating_light: Status change detected"
  graphsUpdate: ":chart_with_upwards_trend: Update uptime graphs"
  commitAuthorName: "Uptime Bot"
  commitAuthorEmail: "uptime@b-cdn.net"
